### ISSUE TITLE
Python 3.5 error in plugin NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by vikrantrathore** [lektor/lektor#229]
While installing a plugin for lektor get an error:

inifile.py", line 172, in to_string
    if isinstance(value, (int, long, float)):

In Python 3.5 they only use "int" not "long" probably its an error specific to Python 3.5

**Comment by singingwolfboy** [comment]
Fixed by https://github.com/mitsuhiko/python-inifile/pull/5.

**Comment by nixjdm** [comment]
This error still presents because that change hasn't made it into a new release of python-inifile. @mitsuhiko  Could you please cut a new release of https://github.com/mitsuhiko/python-inifile for this please? That commit is the only change not released I believe.

**Comment by nixjdm** [comment]
New version of python-inifile just released should fix this.
