### ISSUE TITLE
Fix React warnings

### ISSUE THREAD

**Issue by vanadium23** [lektor/lektor#431]
We couldn't upgrade react in future, if we would not fix warnings from it.

```
Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning
Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
printWarning
```

**Comment by runfalk** [comment]
This is not only related to Lektor itself, but also to its dependencies such as `react-router`

**Comment by nixjdm** [comment]
Fixed in #444

**Comment by runfalk** [comment]
This isn't really fixed, as long as `react-router` is not upgraded. There may be more dependencies that need upgrading to get rid of this warning too.

**Comment by nixjdm** [comment]
Agreed. I closed this too early.
